### ISSUE TITLE
SDK broke: ActiveModel::UnknownAttributeError (unknown attribute 'has_sms_auth' for Signature.):

### ISSUE THREAD

**Issue by altherlex** [hellosign/hellosign-ruby-sdk#121]
After Hellosign update their API the SDK is no longer working properly

The msg I am getting is:

ActiveModel::UnknownAttributeError (unknown attribute 'has_sms_auth' for Signature.):

**Comment by alexmac05** [comment]
sorry to hear this. What call are you making exactly?

**Comment by janetanne** [comment]
hi @altherlex! is this related to the issue that we are discussing in ticket #11562369? 

i am opening a new ticket for you regarding this issue: ticket #11566946. please let me know when you're getting this message (what endpoint are you hitting? can you provide the code snippet of what you're doing so that i can test it myself?)

thanks!

**Comment by janetanne** [comment]
closing, moved to a support ticket.
