### ISSUE TITLE
Add additional content type filtering in parse method

### ISSUE THREAD

**Issue by renderf0x** [hellosign/hellosign-ruby-sdk#22]
Our parse method in `client.rb` only checks for `application/pdf` and treats everything else as json. We should add logic to make sure that

a) text/html responses don't hit the json parser
b) zip files are properly handled

It might look something like this ( from Issue #20 ):

``` ruby
def parse(response)
  if response['content-type'] == 'application/pdf'
    response.body
  elsif response.body.strip.empty?
    {}
  elsif response['content-type'] == 'application/json'
    MultiJson.load response.body.strip
  else
      response.body
  end
end
```

**Comment by lroome** [comment]
We just ran into this issue where we are calling client.signature_request_files(signature_request_id: guid, file_type: 'pdf')
and the server is returning 'text/html'.  The json parser is having a bit of an issue with the pdf file that is in the body

**Comment by asolberg** [comment]
Hi @lroome we actually had a backend issue (since approx. 10/8) that would have affected downloading hard copies of signature requests where the content-type header wasn't being set correctly. We've since fixed the issue and I believe this will probably resolve the problem you were seeing as well. Can you confirm?
